### ISSUE TITLE
Hi bansal. Kesa h?

### ISSUE THREAD

**Issue by vivasvan1** [sahilbansal17/greetify-ios#1]
XD

Bro do you have an apple developer account? 

Wese i wanted to publish an app par apple wale 99$ mang rahe hein kuch developer program bakchodi subscribe karne ke liye. 

agar tere pass ho toh tere naam pe karne ki soch raha tha.

**Comment by sahilbansal17** [comment]
@vivasvan1 Abhi dekha message, nahi yar, I don't have an apple developer account 😛 
I was just trying to create a simple iOS app 😛
